FROM node:22-alpine
WORKDIR /app

# Install OpenSSL for Prisma, curl for healthcheck
RUN apk add --no-cache openssl curl

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

ENV STAGE=dev

EXPOSE 3100
EXPOSE 3101
EXPOSE 9873

CMD [ "yarn", "run", "up" ]
